# FROM python:3.9

# # WORKDIR /app

# # COPY requirements.txt .
# RUN pip install pandas scikit-learn pandas streamlit flask

# # COPY src/ ./src/
# COPY model/ ./model/

# EXPOSE 50002

# ENTRYPOINT [ "executable" ]
