FROM apache/airflow:2.9.1 AS trail_airflow
USER root
RUN apt-get update \
  && apt-get autoremove -yqq --purge \
  && apt-get clean
RUN apt-get install -y pkg-config libhdf5-dev gcc
# Install specific versions of the packages
RUN pip3 install \
    pandas \
    scikit-learn \
    kneed \
    yfinance \
    gcsfs \
    google\
    matplotlib \
    mlflow \
    optuna \
    tensorflow \
    keras \
    psutil \
    pynvml